# Generated by Django 2.0.4 on 2018-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
